export interface ConfirmDestinationConfig {
  slug: string;
  name: string;
  eventLabel: string;
  confirmationLine: string;
  heroImage: string;
  jayVideo: string | null;
  jayPhoto: string;
  watchLink: string;
  calendarLink: string;
  bookingLink: string;
  tags: {
    ghl: string;
    constantContact: string;
  };
  welcomeLetter: string[];
  gifts: {
    cookbook: string | null;
    passportToFreedom: string | null;
    dosAndDonts: string | null;
    childrensBook: string | null;
  };
  essentials: {
    visa: string;
    passport: string;
    vaccines: string;
    currency: string;
    currencyCode: string;
  };
  funFacts: string[];
  funFactsHeading: string;
  funFactsSubheading: string;
  timeZone: string;
  images: {
    strip: string[];
  };
}

const placeholderHero = "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1920";
const placeholderStrip = [
  "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200",
  "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=1200",
  "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200",
  "https://images.unsplash.com/photo-1502780402662-acc01917738e?w=1200",
  "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200",
  "https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200",
];

const stub = (slug: string, name: string, timeZone = "UTC"): ConfirmDestinationConfig => ({
  slug,
  name,
  eventLabel: `${name} Virtual Event`,
  confirmationLine: "Your seat is locked in. We'll see you there.",
  heroImage: placeholderHero,
  jayVideo: null,
  jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
  watchLink: "",
  calendarLink: "",
  bookingLink: "https://maximumimpacttravel.com",
  tags: { ghl: `${name} Info Session`, constantContact: `${name} Info Session` },
  welcomeLetter: [
    "Family,",
    `${name} is calling.`,
    "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
    "Let's get you ready for the magic.",
  ],
  gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
  essentials: {
    visa: "Check requirements for your nationality",
    passport: "Valid 6+ months from travel date",
    vaccines: "Consult your doctor before travel",
    currency: "Local currency",
    currencyCode: "USD",
  },
  funFacts: [
    `${name} is full of stories that have been waiting for you.`,
    `The culture, the food, the people of ${name} will change how you see the world.`,
    `${name} has been shaping civilization in ways most travelers never learn.`,
    `Every corner of ${name} is a chance to remember who you are.`,
    `Travelers say ${name} is the trip they wish they'd taken sooner.`,
  ],
  funFactsHeading: `${name} Isn't Waiting for Someday`,
  funFactsSubheading: "Neither should you.",
  timeZone,
  images: { strip: placeholderStrip },
});

export const destinationsConfirm: Record<string, ConfirmDestinationConfig> = {
  tanzania: {
    slug: "tanzania",
    name: "Tanzania",
    eventLabel: "Tanzania Virtual Event",
    confirmationLine: "Your seat is locked in. We'll see you there.",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/tanzania-zanzibar/",
    tags: { ghl: "Tanzania Info Session", constantContact: "Tanzania Info Session" },
    welcomeLetter: [
      "Family,",
      "Tanzania is where the world began.",
      "I've taken over 2,500 travelers around the world, and Tanzania still takes my breath away. The Serengeti shows you what Earth looked like before we complicated it. Zanzibar shows you what peace feels like.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Visa on arrival or e-visa available",
      passport: "Valid 6+ months from travel date",
      vaccines: "Yellow fever may be required — confirm with your doctor",
      currency: "Tanzanian Shilling",
      currencyCode: "TZS",
    },
    funFacts: [
      "The Serengeti hosts the largest animal migration on Earth — over 2 million wildebeest move together every single year.",
      "Zanzibar was once the spice capital of the world. You can still smell cloves and vanilla in the air.",
      "Tanzania is home to Kilimanjaro — the tallest freestanding mountain on the planet.",
      "The Ngorongoro Crater is the world's largest intact volcanic caldera — and it holds an entire ecosystem inside it.",
      "Zanzibar's Indian Ocean water is so clear you can see 30 feet down on a calm day.",
      "The Serengeti has barely changed in 10,000 years. You are looking at the same landscape our ancestors did.",
    ],
    funFactsHeading: "Tanzania Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Africa/Dar_es_Salaam",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200",
        "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=1200",
        "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200",
        "https://images.unsplash.com/photo-1502780402662-acc01917738e?w=1200",
        "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200",
        "https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200",
        "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200",
      ],
    },
  },
  zanzibar: {
    slug: "zanzibar",
    name: "Zanzibar",
    eventLabel: "Zanzibar Virtual Event",
    confirmationLine: "Your seat is locked in. The island is calling.",
    heroImage: "https://images.unsplash.com/photo-1589552416260-189132d92eed?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/zanzibar/",
    tags: { ghl: "Zanzibar Info Session", constantContact: "Zanzibar Info Session" },
    welcomeLetter: [
      "Family,",
      "Zanzibar is what peace tastes like.",
      "Turquoise water, spice markets that have been trading for a thousand years, and a slowness that resets your nervous system. Stone Town will pull you into a story you didn't know you were part of.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Visa on arrival or e-visa available to most travelers",
      passport: "Valid 6+ months from travel date",
      vaccines: "Yellow fever may apply depending on your routing — confirm with your doctor",
      currency: "Tanzanian Shilling",
      currencyCode: "TZS",
    },
    funFacts: [
      "Zanzibar was the spice capital of the world — cloves, cinnamon, and vanilla still scent the air.",
      "Stone Town is a UNESCO World Heritage Site where Arab, African, Indian, and European stories meet.",
      "The Indian Ocean here is so clear you can see 30 feet down on a calm day.",
      "Zanzibar's reefs are some of the most biodiverse in East Africa.",
      "Freddie Mercury was born here — the island has always been a place that shapes legends.",
      "Sunset on the west coast is something you remember for the rest of your life.",
    ],
    funFactsHeading: "Zanzibar Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Africa/Dar_es_Salaam",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1589552416260-189132d92eed?w=1200",
        "https://images.unsplash.com/photo-1505881502353-a1986add3762?w=1200",
        "https://images.unsplash.com/photo-1535320903710-d993d3d77d29?w=1200",
        "https://images.unsplash.com/photo-1573991233007-1a1f3d31b03f?w=1200",
        "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200",
        "https://images.unsplash.com/photo-1559825481-12a05cc00344?w=1200",
      ],
    },
  },
  ghana: {
    slug: "ghana",
    name: "Ghana",
    eventLabel: "Ghana Virtual Event",
    confirmationLine: "Your seat is locked in. Akwaaba — welcome home.",
    heroImage: "https://images.unsplash.com/photo-1589307357824-1ce8ab90fd9d?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/ghana/",
    tags: { ghl: "Ghana Info Session", constantContact: "Ghana Info Session" },
    welcomeLetter: [
      "Family,",
      "Ghana is the homecoming you didn't know you needed.",
      "From the door of no return at Cape Coast to the drum circles in Accra, this is where memory becomes medicine. Ghanaians say akwaaba — welcome — and they mean it the way few places on earth do.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "E-visa available to most travelers — check requirements for your nationality",
      passport: "Valid 6+ months from travel date",
      vaccines: "Yellow fever vaccination is required for entry — confirm with your doctor",
      currency: "Ghanaian Cedi",
      currencyCode: "GHS",
    },
    funFacts: [
      "Ghana was the first sub-Saharan African nation to gain independence — 1957 changed the continent.",
      "Cape Coast and Elmina Castles hold some of the most powerful history on Earth.",
      "Ghanaian highlife and afrobeats have shaped global music for decades.",
      "Kente cloth from the Ashanti region is woven story — every pattern means something.",
      "Ghana produces some of the finest cocoa in the world — chocolate starts here.",
      "The Year of Return brought hundreds of thousands home. The door is still open.",
    ],
    funFactsHeading: "Ghana Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Africa/Accra",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1589307357824-1ce8ab90fd9d?w=1200",
        "https://images.unsplash.com/photo-1580237072617-771c3ecc4a24?w=1200",
        "https://images.unsplash.com/photo-1604881991720-f91add269bed?w=1200",
        "https://images.unsplash.com/photo-1601469079319-2a1eaa6c8e7c?w=1200",
        "https://images.unsplash.com/photo-1612634837022-2acb86b76a98?w=1200",
        "https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?w=1200",
      ],
    },
  },
  southafrica: {
    slug: "southafrica",
    name: "South Africa",
    eventLabel: "South Africa Virtual Event",
    confirmationLine: "Your seat is locked in. South Africa is ready for you.",
    heroImage: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/south-africa/",
    tags: { ghl: "South Africa Info Session", constantContact: "South Africa Info Session" },
    welcomeLetter: [
      "Family,",
      "South Africa is a continent inside a country.",
      "Cape Town will humble you. The Winelands will spoil you. Kruger will remind you we share this planet with giants. And Soweto will show you what resilience built.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Visa-free entry available to many nationalities — check requirements for yours",
      passport: "Valid 30+ days beyond travel with two blank pages",
      vaccines: "Consult your doctor before travel",
      currency: "South African Rand",
      currencyCode: "ZAR",
    },
    funFacts: [
      "South Africa has 11 official languages — diversity is built into the constitution.",
      "Table Mountain is one of the oldest mountains on Earth — older than the Himalayas, the Rockies, and the Alps.",
      "Kruger National Park is bigger than some countries and home to the Big Five.",
      "The Cape Winelands produce some of the most acclaimed wines in the world.",
      "Robben Island is where Mandela spent 18 years — and where the world learned what dignity looks like.",
      "South Africa has three capital cities — Pretoria, Cape Town, and Bloemfontein.",
    ],
    funFactsHeading: "South Africa Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Africa/Johannesburg",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200",
        "https://images.unsplash.com/photo-1591742708930-0fef39e7fbb1?w=1200",
        "https://images.unsplash.com/photo-1576487248805-cf45f6bcc67f?w=1200",
        "https://images.unsplash.com/photo-1547970810-dc1eac37d174?w=1200",
        "https://images.unsplash.com/photo-1484318571209-661cf29a69c3?w=1200",
        "https://images.unsplash.com/photo-1604431696980-07e518647bf2?w=1200",
      ],
    },
  },
  kenya: {
    slug: "kenya",
    name: "Kenya",
    eventLabel: "Kenya Virtual Event",
    confirmationLine: "Your seat is locked in. Karibu — Kenya is waiting.",
    heroImage: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/kenya/",
    tags: { ghl: "Kenya Info Session", constantContact: "Kenya Info Session" },
    welcomeLetter: [
      "Family,",
      "Kenya is where the safari was born.",
      "The Maasai Mara is the kind of place that makes you understand your size in the universe — in the best possible way. The Maasai people will teach you something about presence you won't find in a book.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Electronic Travel Authorization required — apply online before travel",
      passport: "Valid 6+ months from travel date with two blank pages",
      vaccines: "Yellow fever may apply depending on your routing — confirm with your doctor",
      currency: "Kenyan Shilling",
      currencyCode: "KES",
    },
    funFacts: [
      "The Great Migration sweeps through the Maasai Mara every year — over a million wildebeest crossing the Mara River.",
      "Kenya sits on the equator and contains snow-capped peaks, deserts, savannas, and tropical coastline.",
      "Mount Kenya is the second-highest mountain in Africa.",
      "The Maasai are one of the most recognized cultures on Earth — and they still live the way their ancestors did.",
      "Lake Nakuru turns pink with millions of flamingos.",
      "Kenya produces some of the finest coffee and tea in the world.",
    ],
    funFactsHeading: "Kenya Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Africa/Nairobi",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200",
        "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200",
        "https://images.unsplash.com/photo-1535941339077-2dd1c7963098?w=1200",
        "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200",
        "https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200",
        "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200",
      ],
    },
  },
  ethiopia: {
    slug: "ethiopia",
    name: "Ethiopia",
    eventLabel: "Ethiopia Virtual Event",
    confirmationLine: "Your seat is locked in. Ethiopia is ready to meet you.",
    heroImage: "https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/ethiopia/",
    tags: { ghl: "Ethiopia Info Session", constantContact: "Ethiopia Info Session" },
    welcomeLetter: [
      "Family,",
      "Ethiopia is older than almost everything you think you know.",
      "The rock-hewn churches of Lalibela. The ancient obelisks of Axum. The coffee ceremony that taught the world how to drink. Ethiopia is the cradle of so much that we take for granted.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "E-visa available to most travelers before arrival",
      passport: "Valid 6+ months from travel date",
      vaccines: "Yellow fever may apply depending on your routing — confirm with your doctor",
      currency: "Ethiopian Birr",
      currencyCode: "ETB",
    },
    funFacts: [
      "Ethiopia is the only African country never colonized.",
      "Coffee was discovered here — every cup in the world traces back to Ethiopia.",
      "Lalibela's 11 rock-hewn churches were carved out of solid stone in the 12th century.",
      "Ethiopia uses its own calendar — and it's about seven years behind the rest of the world.",
      "Lucy, one of the oldest human ancestors ever found, was discovered here.",
      "Ethiopian cuisine — injera, doro wat, kitfo — is unlike anything else on the continent.",
    ],
    funFactsHeading: "Ethiopia Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Africa/Addis_Ababa",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1575223970966-76ae61ee7838?w=1200",
        "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200",
        "https://images.unsplash.com/photo-1589307357824-1ce8ab90fd9d?w=1200",
        "https://images.unsplash.com/photo-1604881991720-f91add269bed?w=1200",
        "https://images.unsplash.com/photo-1612634837022-2acb86b76a98?w=1200",
        "https://images.unsplash.com/photo-1605648916361-9bc12ad6a569?w=1200",
      ],
    },
  },
  egypt: {
    slug: "egypt",
    name: "Egypt",
    eventLabel: "Egypt Virtual Event",
    confirmationLine: "Your seat is locked in. 5,000 years of story is waiting.",
    heroImage: "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/egypt/",
    tags: { ghl: "Egypt Info Session", constantContact: "Egypt Info Session" },
    welcomeLetter: [
      "Family,",
      "Egypt is the original wonder of the world.",
      "Standing in front of the Great Pyramid will recalibrate you. Sailing the Nile at sunset will move you. And the new Grand Egyptian Museum is going to change how the world tells this story.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "E-visa available to most travelers — check requirements for your nationality",
      passport: "Valid 6+ months from travel date",
      vaccines: "Consult your doctor before travel",
      currency: "Egyptian Pound",
      currencyCode: "EGP",
    },
    funFacts: [
      "The Great Pyramid of Giza is the only Wonder of the Ancient World still standing.",
      "The Nile is the longest river on Earth — and civilization itself was built along it.",
      "Cleopatra lived closer in time to the moon landing than to the building of the pyramids.",
      "The Grand Egyptian Museum is the largest archaeological museum in the world.",
      "Egyptians invented the 365-day calendar, paper, and one of the first written languages.",
      "The Red Sea has some of the most spectacular reef diving on Earth.",
    ],
    funFactsHeading: "Egypt Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Africa/Cairo",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?w=1200",
        "https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=1200",
        "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=1200",
        "https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=1200",
        "https://images.unsplash.com/photo-1594735797933-d0501ba2fe65?w=1200",
        "https://images.unsplash.com/photo-1569321633216-f10ad6e7d35f?w=1200",
      ],
    },
  },
  morocco: {
    slug: "morocco",
    name: "Morocco",
    eventLabel: "Morocco Virtual Event",
    confirmationLine: "Your seat is locked in. Morocco is ready to enchant you.",
    heroImage: "https://images.unsplash.com/photo-1539020140153-e479b8c5c2e2?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/morocco/",
    tags: { ghl: "Morocco Info Session", constantContact: "Morocco Info Session" },
    welcomeLetter: [
      "Family,",
      "Morocco is a feast for every sense you have.",
      "The medinas of Marrakech and Fes feel like time travel. The Sahara at night will quiet every loud thing in your life. And Moroccan hospitality is its own kind of magic.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Visa-free entry available to many nationalities — check requirements for yours",
      passport: "Valid 6+ months from travel date",
      vaccines: "Consult your doctor before travel",
      currency: "Moroccan Dirham",
      currencyCode: "MAD",
    },
    funFacts: [
      "Fes el-Bali is the largest car-free urban area in the world — and a UNESCO World Heritage Site.",
      "Morocco's medinas have been continuously inhabited for over 1,000 years.",
      "The Sahara stretches across Morocco's southeast — a sea of dunes that turns gold at sunset.",
      "Mint tea is more than a drink here — it's a ceremony, a welcome, and an art form.",
      "Morocco is the only African country with both Atlantic and Mediterranean coastlines.",
      "The blue city of Chefchaouen is painted entirely in shades of indigo.",
    ],
    funFactsHeading: "Morocco Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Africa/Casablanca",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1539020140153-e479b8c5c2e2?w=1200",
        "https://images.unsplash.com/photo-1548019979-e8ab35691ed9?w=1200",
        "https://images.unsplash.com/photo-1597211833712-5e41faa202ea?w=1200",
        "https://images.unsplash.com/photo-1553855985-8bbc3a2d4a47?w=1200",
        "https://images.unsplash.com/photo-1531001142232-9e21d2474392?w=1200",
        "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=1200",
      ],
    },
  },
  dubai: {
    slug: "dubai",
    name: "Dubai",
    eventLabel: "Dubai Virtual Event",
    confirmationLine: "Your seat is locked in. Dubai is ready to dazzle you.",
    heroImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/dubai/",
    tags: { ghl: "Dubai Info Session", constantContact: "Dubai Info Session" },
    welcomeLetter: [
      "Family,",
      "Dubai is what happens when imagination has no ceiling.",
      "From the top of the Burj Khalifa to a quiet camel ride through the desert at dawn, this city moves between extremes with style. You will not see another place like it on this planet.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Visa-free entry available to many nationalities — check requirements for yours",
      passport: "Valid 6+ months from travel date",
      vaccines: "Consult your doctor before travel",
      currency: "UAE Dirham",
      currencyCode: "AED",
    },
    funFacts: [
      "The Burj Khalifa is the tallest building in the world — 2,717 feet of pure ambition.",
      "Dubai built the world's largest man-made islands — visible from space.",
      "Over 200 nationalities live and work here — it's one of the most diverse cities on Earth.",
      "The Dubai Mall is the largest in the world by total area.",
      "Just 60 years ago, Dubai was a small fishing village. Today it's a global capital.",
      "The desert just outside the city is one of the most peaceful places you'll ever experience at sunrise.",
    ],
    funFactsHeading: "Dubai Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "Asia/Dubai",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200",
        "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200",
        "https://images.unsplash.com/photo-1546412414-e1885259563a?w=1200",
        "https://images.unsplash.com/photo-1582672060674-bc2bd808a8f5?w=1200",
        "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?w=1200",
        "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=1200",
      ],
    },
  },
  brazil: {
    slug: "brazil",
    name: "Brazil",
    eventLabel: "Brazil Virtual Event",
    confirmationLine: "Your seat is locked in. Brazil is ready to move you.",
    heroImage: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/brazil/",
    tags: { ghl: "Brazil Info Session", constantContact: "Brazil Info Session" },
    welcomeLetter: [
      "Family,",
      "Brazil is the largest African country outside of Africa.",
      "Salvador's culture, Rio's rhythm, the Amazon's quiet power — Brazil holds more of our story than most travelers realize. This is a homecoming dressed as a vacation.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Requirements vary by nationality — many travelers can apply for an e-visa online",
      passport: "Valid 6+ months from travel date",
      vaccines: "Consult your doctor before travel",
      currency: "Brazilian Real",
      currencyCode: "BRL",
    },
    funFacts: [
      "Salvador da Bahia has the largest African-descendant population outside of Africa.",
      "The Amazon produces about 20% of the world's oxygen.",
      "Brazil is the only country in South America that speaks Portuguese.",
      "Capoeira — the dance-fight-art form — was created by enslaved Africans in Brazil.",
      "Carnival in Rio is the largest party on Earth — over 2 million people in the streets each day.",
      "Christ the Redeemer was named one of the New Seven Wonders of the World.",
    ],
    funFactsHeading: "Brazil Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "America/Sao_Paulo",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1200",
        "https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=1200",
        "https://images.unsplash.com/photo-1544989164-31dc3c645987?w=1200",
        "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=1200",
        "https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=1200",
        "https://images.unsplash.com/photo-1564661123776-6c5e4e4bd1f9?w=1200",
      ],
    },
  },
  caribbean: {
    slug: "caribbean",
    name: "The Caribbean",
    eventLabel: "Caribbean Virtual Event",
    confirmationLine: "Your seat is locked in. The islands are calling.",
    heroImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/caribbean/",
    tags: { ghl: "Caribbean Info Session", constantContact: "Caribbean Info Session" },
    welcomeLetter: [
      "Family,",
      "The Caribbean is rest with a backbone.",
      "Beyond the postcard beaches is a region that survived everything and still chose joy. The food, the music, the people — every island is its own world, and we curate the trip to match yours.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Requirements vary by island and nationality — most travelers enter visa-free",
      passport: "Valid 6+ months from travel date",
      vaccines: "Consult your doctor before travel",
      currency: "Varies by island — USD widely accepted",
      currencyCode: "USD",
    },
    funFacts: [
      "The Caribbean spans more than 700 islands across 13 sovereign nations.",
      "Reggae, soca, calypso, dancehall, zouk — the Caribbean shaped the soundtrack of the world.",
      "Some of the clearest water on Earth is in the Bahamas, Turks and Caicos, and the Grenadines.",
      "Jerk, curry, mofongo, conch — Caribbean cuisine is one of the most diverse on the planet.",
      "Carnival traditions across the islands trace back to West African roots.",
      "The region holds some of the oldest standing colonial-era architecture in the Americas.",
    ],
    funFactsHeading: "The Caribbean Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "America/Barbados",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200",
        "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=1200",
        "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1200",
        "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
        "https://images.unsplash.com/photo-1548574505-5e239809ee19?w=1200",
        "https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=1200",
      ],
    },
  },
  gullah: {
    slug: "gullah",
    name: "Gullah Geechee",
    eventLabel: "Gullah Geechee Virtual Event",
    confirmationLine: "Your seat is locked in. The Lowcountry is ready to share its story.",
    heroImage: "https://images.unsplash.com/photo-1593974750835-e1ad6f87c3ad?w=1920",
    jayVideo: null,
    jayPhoto: "https://storage.googleapis.com/msgsndr/KSmohoW4bdBXMkPu9h7U/media/69538e8aec06c504ac9c62ca.jpg",
    watchLink: "",
    calendarLink: "",
    bookingLink: "https://maximumimpacttravel.com/destination/gullah-geechee/",
    tags: { ghl: "Gullah Geechee Info Session", constantContact: "Gullah Geechee Info Session" },
    welcomeLetter: [
      "Family,",
      "Gullah Geechee country is the most direct living connection to West Africa in the Americas.",
      "From the Sea Islands of South Carolina and Georgia to the language, the food, the spiritual practices — this culture preserved what so much of the diaspora lost. We don't visit. We listen.",
      "Your spot is locked in. Between now and the session, explore everything below. Come ready to be inspired.",
      "Let's get you ready for the magic.",
      "— Jay Cameron",
      "Travel Architect and Founder of Maximum Impact Travel",
    ],
    gifts: { cookbook: null, passportToFreedom: null, dosAndDonts: null, childrensBook: null },
    essentials: {
      visa: "Domestic travel within the United States — no visa required for US travelers",
      passport: "Government-issued ID required for travel",
      vaccines: "Consult your doctor before travel",
      currency: "US Dollar",
      currencyCode: "USD",
    },
    funFacts: [
      "The Gullah Geechee Cultural Heritage Corridor stretches from Wilmington, NC to Jacksonville, FL.",
      "The Gullah language is a Creole that preserves grammar and vocabulary from West African languages.",
      "Sweetgrass basket weaving in the Lowcountry traces directly back to West Africa.",
      "Many staples of Southern cuisine — rice dishes, okra, gumbo — are Gullah Geechee contributions.",
      "The Sea Islands were one of the first places freedom was declared during the Civil War.",
      "Gullah Geechee culture has shaped American music, food, language, and spirituality for centuries.",
    ],
    funFactsHeading: "Gullah Geechee Isn't Waiting for Someday",
    funFactsSubheading: "Neither should you.",
    timeZone: "America/New_York",
    images: {
      strip: [
        "https://images.unsplash.com/photo-1593974750835-e1ad6f87c3ad?w=1200",
        "https://images.unsplash.com/photo-1518562923204-2cf5b67c5b1d?w=1200",
        "https://images.unsplash.com/photo-1572455024129-c2d4f5b5d6b9?w=1200",
        "https://images.unsplash.com/photo-1564504901834-bb1207b4673f?w=1200",
        "https://images.unsplash.com/photo-1552083375-1447ce886485?w=1200",
        "https://images.unsplash.com/photo-1565619624427-d57f5e6b6b08?w=1200",
      ],
    },
  },
};

export const defaultConfirmDestination: ConfirmDestinationConfig = {
  ...stub("default", "Maximum Impact Travel"),
  eventLabel: "Maximum Impact Travel Virtual Event",
  funFactsHeading: "The World Isn't Waiting for Someday",
};

export const getConfirmDestination = (slug?: string): ConfirmDestinationConfig => {
  if (!slug) return defaultConfirmDestination;
  return destinationsConfirm[slug.toLowerCase()] ?? defaultConfirmDestination;
};